# ~/.config/starship.toml

# Use custom format
format = '''
$directory$nodejs$rust$php
$git_branch$git_status [⇒](bold green) '''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
# Disable the blank line at the start of the prompt
add_newline = false

[rust]
format = '[~>]($style) [$symbol$version]($style) '

[nodejs]
format = '[~>]($style) [🤖 $version]($style) '

[php]
format = '[~>]($style) [$symbol$version]($style) '

[aws]
format = ''
style = 'bold blue'
symbol = '🅰 '
[aws.region_aliases]
ap-southeast-2 = 'au'
us-east-1 = 'va'

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[git_status]
style = "bold purple"
